### ISSUE TITLE
Unsupported event type: issue_comment

### ISSUE THREAD

**Issue by kevinsmith** [daun/playwright-report-summary#203]
We're triggering playwright runs using slash commands in our PR comments, which means the action is configured like this:

```yaml
on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/playwright') }}
```

Is it possible to get this report summary to support this event type?
