### ISSUE TITLE
"Report file … not found." due to custom `working-directory`

### ISSUE THREAD

**Issue by jhogervorst** [daun/playwright-report-summary#224]
I initially configured my workflow like this:

```yaml
jobs:
  test:
    defaults:
      run:
        working-directory: ${{ github.workspace }}/tests

    steps:
      - run: PLAYWRIGHT_JSON_OUTPUT_NAME=results.json npx playwright test --reporter json

      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: results.json
```

However, I then got the following error:

```
Error: Report file results.json not found. Make sure Playwright is configured to generate a JSON report.
````

It turned out that the default `working-directory` only applies to `run` steps, so not to this action. To make it work, I had to modify my workflow like this:

```yaml
jobs:
  test:
    defaults:
      run:
        working-directory: ${{ github.workspace }}/tests

    steps:
      - run: PLAYWRIGHT_JSON_OUTPUT_NAME=results.json npx playwright test --reporter json

      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: tests/results.json
          #            ^^^^^
```

I'm posting this here in case anyone runs into the same problem and looks for a solution. Perhaps it could also be useful to add to the readme/documentation.

**Comment by daun** [comment]
Thanks for reporting. I'm not familiar with the `working-directory` config, but it looks to me like the action should just support it out of the box, no?

**Comment by daun** [comment]
Reading through the [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/setting-a-default-shell-and-working-directory#setting-default-shell-and-working-directory), the `defaults.run` config applies to all `run` steps executed on the local shell, which I interpret to mean it wouldn't apply to actions.

The canonical way of doing this would probably also use the `working-directory` setting on the report step. Not sure if that can also be set through the top-level `defaults` key, though.

```yaml
      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file:results.json
          working-directory: ${{ github.workspace }}/tests
```
