### ISSUE TITLE
Input PR id as input parameter

### ISSUE THREAD

**Issue by awolfson2** [daun/playwright-report-summary#249]
Maybe this is already supported, but i'm running a workflow from a slack bot (api triggered).  I want to update a PR that was created in a different workflow and comment my playwright results in that PR.  I'm using a few other actions and input a pr_id that associates the action with the results.  Does your action do this or something similar?

thank you!

**Comment by daun** [comment]
Hi! No, this isn't currently supported, I'm afraid.

It would involve two distinct steps I think:

1. Get the playwright report data, which would be somewhat difficult from outside the action triggering the tests
2. Find the current PR and comment on it, which would be the easy part.

I'm currently pretty busy with client work, but if you come up with a PR, I'm happy to take a look!

**Comment by daun** [comment]
@awolfson2 Okay, that sounds doable.

How would I give you access? PRs are open I think, but let me know if it needs anything else!

**Comment by darmbrust** [comment]
Made an attempt... completely untested though.
https://github.com/daun/playwright-report-summary/pull/290

**Comment by daun** [comment]
Thanks @darmbrust, this is released as version 3.10. I've renamed the input `pr-number` for clarity.

This is how it would look for this action:

```yaml
  - uses: jwalton/gh-find-current-pr@v1
    id: pr
  - uses: daun/playwright-report-summary@v3
    with:
      report-file: results.json
      pr-number: ${{ steps.pr.outputs.number }}
```
