### ISSUE TITLE
Update latest gh message report instead create new one on each run

### ISSUE THREAD

**Issue by eleven4y** [daun/playwright-report-summary#66]
Problem:
Now, each run of github action with playwright, which send report summary generate new comment message to pull with results and create rubbish to pull 

- it's harder to watch the pool
- comments with irrelevant results remain

Solution:
Instead of creating a new comment with summary results, update the last post

**Comment by daun** [comment]
The action is set up to update existing comments instead of creating a new one with each run. Are you saying that's not happening?

**Comment by eleven4y** [comment]
> The action is set up to update existing comments instead of creating a new one with each run. Are you saying that's not happening?

y, i looked at doc of action and surprised why in our workflow we received new comments for each run of job with playwright tests and report

example of usage

```
      - uses: daun/playwright-report-summary@v2
        with:
          github-token: ${{ secrets.APP_GITHUB_TOKEN }}
          report-file: tests/playwright-report/test_result_json.json
```
