### ISSUE TITLE
Different comment title means different updated comment.

### ISSUE THREAD

**Issue by urothis** [daun/playwright-report-summary#68]
I really like the update comment functionality, but I really wish it was configurable to allow for better monorepo usage.

For example:
    We have 3 suites of playwright running on a single pr, depending upon changes made in that pr, and right now we have to check the comment history to actually see all 3 suites even though they are titled differently.

I would like it to only update the comment that matches the title set( or creates a new comment), instead of modifying the title of the singular comment.

**Comment by daun** [comment]
Sounds like a reasonable use case to support. What's the best way to id unique jobs? Are you running the playwright suits from different jobs, or from different workflows?

**Comment by urothis** [comment]
Yes and Yes. 
I was thinking using the existing Title as the unique ID might be the best way.
Might be the most malleable solution atleast.

**Comment by daun** [comment]
By "title" you mean the `comment-title` input param that determines the title of the comment created by the action?

**Comment by urothis** [comment]
Correct, could also just be a separate string param. 
'job-name' or something?

**Comment by daun** [comment]
Can you try `v3` of the action? It now tags each report by the name of the workflow file. That should be enough to allow multiple workflows per PR.

For more specific cases and multiple jobs per workflow, there's now a new `report-tag` input to allow uniquely identifying report runs:

```yaml
- uses: daun/playwright-report-summary@v3
  with:
    report-file: results.json
    report-tag: report-summary-1

- uses: daun/playwright-report-summary@v3
  with:
    report-file: results.json
    report-tag: report-summary-2
```
